NUM_WORKERS: 0
BATCH_SIZE: 8
NUM_EPOCHS: 20
LEARNING_RATE: 0.00005
WEIGHT_DECAY: 0.0001
MOMENTUM: 0.9
DROPOUT_RATE: 0.25
EARLY_STOPPING_PATIENCE: 30
AVERAGE: "macro"
PRINT_EVERY: 9999
SAVE_PATH: "artifacts/densenet121"
SAVE_MODEL: true
SAVE_METRICS: true
SAVE_PATIENCE: 1
SHUFFLE: True
